version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask_api
    logging:
      driver: "local"
      options:
        max-size: "10m"
  flask_api:
    build:
      context: flask_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
