version: "3.9"
# Each service is a container
services:
  nginx:
    image: nginx
    # in docker-compose, paths are relative to the docker-compose file
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    # specify that the flask_api container must be running before the nginx container
    depends_on:
      - flask_api
    # specify that logging should be managed in a rotating basis
    logging:
      driver: "local"
      options:
        max-size: "10m"
  flask_api:
    # specify where the container should be build and run from
    build:
      context: flask_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # specify that logging should be managed in a rotating basis
    logging:
      driver: "local"
      options:
        max-size: "10m"
